swagger: '2.0'
info:
  version: 1.0.0
  title: api01
  x-ibm-name: api01
basePath: /api011
x-ibm-configuration:
  properties:
    target-url:
      value: 'https://1a8ef218-51b7-4127-a060-985d13ef25bf.mock.pstmn.io/mock'
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: $httpVerb()='POST' and $operationPath()='/redaction_and_log'
              execute:
                - parse:
                    version: 2.1.0
                    title: parse
                    parse-settings-reference:
                      default: apic-default-parsesettings
                - redact:
                    version: 2.0.0
                    title: redact
                    redactions:
                      - action: redact
                        path: request_body.**.key1
                      - action: redact
                        path: message.body.key2
                    root: ''
                - invoke:
                    version: 2.2.0
                    title: invoke
                    backend-type: detect
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    http-version: HTTP/1.1
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    graphql-send-type: detect
                    websocket-upgrade: false
                    target-url: $(target-url)
                - parse:
                    version: 2.1.0
                    title: parse
                    parse-settings-reference:
                      default: apic-default-parsesettings
                - redact:
                    version: 2.0.0
                    title: redact
                    redactions:
                      - action: redact
                        path: message.body.name
                    root: ''
            - condition: $httpVerb()='POST' and $operationPath()='/log'
              execute:
                - log:
                    version: 2.1.0
                    title: log
                    log-level: default
                    mode: gather-only
                - redact:
                    version: 2.0.0
                    title: redact
                    redactions:
                      - action: redact
                        path: request_body.**.key1
                      - action: redact
                        path: $.item.key2
                    root: log
                - log:
                    version: 2.1.0
                    title: log
                    log-level: default
                    mode: send-only
                - invoke:
                    version: 2.2.0
                    title: invoke
                    backend-type: detect
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    http-version: HTTP/1.1
                    timeout: 60
                    verb: keep
                    chunked-uploads: true
                    persistent-connection: true
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    graphql-send-type: detect
                    websocket-upgrade: false
                    target-url: $(target-url)
  activity-log:
    enabled: true
    success-content: payload
    error-content: payload
    preserved-request-header: []
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    options:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    parameters: []
  /redaction_and_log:
    post:
      responses:
        '200':
          description: success
  /log:
    parameters: []
    post:
      responses:
        '200':
          description: success
schemes:
  - https
parameters: {}
